### ISSUE TITLE
Not port 1900

### ISSUE THREAD

**Issue by tielur** [nerves-project/nerves_ssdp_server#5]
Hey I'm trying to debug an issue and **I think** one problem I'm seeing is that `NOTIFY` response to an `M-SEARCH` request is not sending port `1900`, in my case it's sending port `55274`.

I took a look at the code and I'm not sure why it would be doing that. Inside of [server.ex](https://github.com/ghitchens/nerves_ssdp_server/blob/master/lib/ssdp_server/server.ex#L136) I see the module attribute for the `@mcast_port` set to `1900`. 

I may be completely off and this is how it's suppose to work as well, but let me show you how I'm testing it.

I'm using a script I found that uses python to send out `M-SEARCH` and then shows the replies.

```python
#!/usr/bin/env python2
import socket
import sys

dst = "239.255.255.250"
if len(sys.argv) > 1:
    dst = sys.argv[1]
st = "upnp:rootdevice"
if len(sys.argv) > 2:
    st = sys.argv[2]

msg = [
    'M-SEARCH * HTTP/1.1',
    'Host:239.255.255.250:1900',
    'ST:%s' % (st,),
    'Man:"ssdp:discover"',
    'MX:1',
    '']

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
s.settimeout(10)
s.sendto('\r\n'.join(msg), (dst, 1900) )

while True:
    try:
        data, addr = s.recvfrom(32*1024)
    except socket.timeout:
        break
    print "[+] %s\n%s" % (addr, data)
```

I'm running that via `python2 ssdp-query.py 239.255.255.250 ssdp:all`

All of the other devices on my network respond with `[+] ('IP', 1900)`, where `IP` is their local `IP`

Here's an example:
```
[+] ('192.168.86.250', 1900)
HTTP/1.1 200 OK
Server: HDHomeRun/1.0 UPnP/1.0
ST: uuid:01C50CAA-0060-3B17-90EF-963702BBA053
Location: http://192.168.86.250:80/dms/device.xml
Cache-Control: max-age=1800
USN: uuid:01C50CAA-0060-3B17-90EF-963702BBA053
Ext:
Content-Length: 0
Date: Thu, 20 May 2021 15:06:49 GMT
```

When my raspberry pi that is running `nerves_ssdp_server` replies, it looks like this:
```
[+] ('192.168.86.46', 55274)
HTTP/1.1 200 OK
LOCATION: http://192.168.86.46:80/description.xml
HOST: 192.168.86.46
CACHE-CONTROL: max-age=60
EXT: 
HUE-BRIDGEID: b827ebFFFEe57bc6
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0
ST: uuid:2f402f80-da50-11e1-9b23-001788255acc
USN: uuid:2f402f80-da50-11e1-9b23-001788255acc
```
Notice how it's replying with port `55274`? All of my other devices have port `1900` there like the first example just above.

I'm not entirely sure if this is my issue but in comparing other devices this seems to be different.

**Comment by ghitchens** [comment]
Hi Tyler.  I haven’t worked with this code for some time, however, I know that @captchrisd has been working with it in the last few weeks and it is working for him to do discovery on windows.    

I don’t use python much, but it looks like your code is looking at the SOURCE address/port of the resulting NOTIFY rather than the destination of the NOTIFY.  

Realize that SSDP is both a unicast and multicast protocol.    You are using the unicast mode below (response to an M SEARCH).   You are receiving the response, so obviously it is replying unicast TO port 1900, since that is the port your are listening on, and you get the message.  

The source port of the response is, I believe, not relevant and will vary depending on implementation.     Most advanced linux devices will choose an ephermal port (like nerves_ssdp_server does).    There is no requirement in the protocol that this port be 1900, however simple embedded devices that don’t do port allocation and management will usually use 1900 since they know they only will ever have one process doing SSDP.

You never said the problem you are trying to debug that prompted you to look at the source port.   I wonder if it is that you don't get NOTIFY announcements unless you send an M-SEARCH?   If so, that might be because you are not joining the multicast group on your socket in your python code.   

Or maybe I misunderstand the problem you are having..   From what I can see, you are sending a search and getting a response, so the problem the prompted the question must be elsewhere?

If you give me a clue what prompted the debugging I might be able to help further.

Garth

**Comment by tielur** [comment]
Hi Garth,
Thanks for the reply. What you mentioned about the difference between the SOURCE address/port and the destination makes sense. I was just taking a shot in that dark that this may be a problem. 

I opened up wireshark and filtered it to SSDP and do indeed see this now:
`User Datagram Protocol, Src Port: 55274, Dst Port: 1900`

Using wireshark I think I can confirm that my`nerves_ssdp_server` is responding to an m-search, specifically 
```
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 3
```

I think it may just come down to my implementation and/or lack of understanding on providing the correct custom fields to `Nerves.SSDPServer.publish/3`

**Comment by tielur** [comment]
I don't believe this an issue with `nerves_ssdp_server`
